<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfAuthUser extends BasesfAuthUser
{
    public $cacheCrendentials = null;
    
    public function preInsert($event)
    {
        $this->activate_hash = sfAuthUtil::getHashedPasswordBySaltAndString('activate', uniqid());
        return $event;
    }
    
    public function setPassword($value)
    {
        
        $this->setSalt(uniqid());
        parent::_set('password', sfAuthUtil::getHashedPasswordBySaltAndString($this->getSalt(), $value));
    }
    
    public function getAllCredentials()
    {
        if (!$this->cacheCrendentials) {
            $credentials = Doctrine::getTable('sfAuthCredential')->getAllByUser($this);
            $this->cacheCrendentials = $credentials;
        }
        
        return $this->cacheCrendentials;
    }
    
    public function reloadAllCredentials()
    {
        $this->cacheCredentials = null;
        return $this->getAllCredentials();
    }
}