<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfAuthIdentityTable extends Doctrine_Table
{
    public function getAllByUser(sfUser $user)
    {
        $q = $this->createQuery('i');
        $q->addWhere('i.sf_auth_user_id = ?', $user->getId());
        
        return $q->execute();
    }
    
    public function findOneByIdUser($id, sfUser $user)
    {
        $q = $this->createQuery('i');
        $q->addWhere('i.id = ? AND i.sf_auth_user_id = ?', array($id, $user->getId()));
        
        return $q->fetchOne();
    }
}